"""BD3

Revision ID: 009926bc4398
Revises: 
Create Date: 2026-09-29 17:30:05.948714

"""
from typing import Sequence, Union

from DATA.presets import COEFFICIENTS, ROBOTS
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '009926bc4398'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    coef_table = op.create_table('coefficients',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('opt', sa.Float(), nullable=False),
    sa.Column('base', sa.Float(), nullable=False),
    sa.Column('pess', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    robot_table = op.create_table('robots',
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('accum_life', sa.Integer(), nullable=False),
    sa.Column('mass', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('max_speed', sa.Float(), nullable=False),
    sa.Column('navigation_type', sa.String(), nullable=False),
    sa.Column('charge_time', sa.Float(), nullable=False),
    sa.Column('work_time', sa.Float(), nullable=False),
    sa.Column('efficiency', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('operationg_conditions', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cases',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('robot_count', sa.Integer(), nullable=False),
    sa.Column('tariff', sa.Integer(), nullable=False),
    sa.Column('shortened', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_case_user_name')
    )
    op.create_index('idx_cases_user', 'cases', ['user_id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('source_file', sa.String(length=512), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id'),
    sa.UniqueConstraint('case_id', name='uq_dataset_case')
    )
    op.create_index('idx_datasets_data', 'datasets', ['data'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###

    op.bulk_insert(coef_table, COEFFICIENTS)
    op.bulk_insert(robot_table, [r.model_dump() for r in ROBOTS])

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_datasets_data', table_name='datasets', postgresql_using='gin')
    op.drop_table('datasets')
    op.drop_index('idx_cases_user', table_name='cases')
    op.drop_table('cases')
    op.drop_table('users')
    op.drop_table('robots')
    op.drop_table('coefficients')
    # ### end Alembic commands ###
